name: push-develop
on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          cat $HOME/files_modified.json
          echo '${{ steps.file_changes.outputs.files_modified}}'
      - name: metadata file
        run: |
          cat $HOME/workflow-templates/mainBranch-workflows.properties.json
          echo '${{ inputs.name }}'
