name: push-develop
on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
      - name: test
        run: echo '${{ steps.file_changes.outputs.files_modified}}'
      - name: test-1
        if: ${{contains(steps.file_changes.outputs.files_modified,'secondProject') && !contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run: echo 'Second Project changes'
      - name: test-2
        if: ${{!contains(steps.file_changes.outputs.files_modified,'secondProject') && contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run: echo 'selfHostedRunners project changes'
      - name: test-3
        if: ${{contains(steps.file_changes.outputs.files_modified,'secondProject') && contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run: echo 'selfHostedRunners and second project changes'
      - name: test-4
        if: ${{!contains(steps.file_changes.outputs.files_modified,'secondProject') && !contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run: echo 'except selfHostedRunners and second project changes'
