name: push-develop
on:
  push:
    branches:
      - main
env:
  PROJECT_SELECTION:
  PROJECT_PATH:
  OUTPUT_PATH:
jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Detect file changes
      id: file_changes
      run: |
        echo "Added files:"
        echo "${{ steps.file_changes.outputs.added }}"
        echo "Modified files:"
        echo "${{ steps.file_changes.outputs.modified }}"
        echo "Deleted files:"
        echo "${{ steps.file_changes.outputs.deleted }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Print file changes
      run: |
        echo "Changed files:"
        echo "${{ steps.file_changes.outputs.changed_files }}"

      


  
        

