name: push-develop
on:
  push:
    branches:
      - main
env:
  projectSelection: ""
  projectPath: ""
  outPutPath: ""
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string

      - name: check secondProject changes
        if: ${{contains(steps.file_changes.outputs.files_modified,'secondProject') && !contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run: |
          echo "projectSelection=secondProject" >> $GITHUB_ENV
          echo "projectPath=C:\Users\Admin\self-hosted-runners\secondProject" >> $GITHUB_ENV
          echo "outPutPath=C:\output\angular\secondProject" >> $GITHUB_ENV

      - name: check selfHostedRunners changes
        if: ${{!contains(steps.file_changes.outputs.files_modified,'secondProject') && contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run: |
          echo "projectSelection=selfHostedRunners" >> $GITHUB_ENV
          echo "projectPath=C:\Users\Admin\self-hosted-runners\selfHostedRunners" >> $GITHUB_ENV
          echo "outPutPath=C:\output\angular\secondProject" >> $GITHUB_ENV

      - name:  check all project changes
        if: ${{contains(steps.file_changes.outputs.files_modified,'secondProject') && contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run:  echo "projectSelection=all" >> $GITHUB_ENV

      - name: other file changes check
        if: ${{!contains(steps.file_changes.outputs.files_modified,'secondProject') && !contains(steps.file_changes.outputs.files_modified,'selfHostedRunners')}} 
        run:  echo "$env.projectSelection=nothing" >> $GITHUB_ENV
      


  build: 
    runs-on: self-hosted
    needs: [changes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: display-item
        run:  echo ${{env.projectSelection}}
        

