name: File Changes Workflow

on:
  push:
    branches:
      - main
env:
  FILES:
  PROJECT_SELECTIONS:

jobs:
  check_changes:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Detect file changes
      id: file_changes
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const compareCommits = await github.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: context.payload.before,
            head: context.payload.after,
          });
          const changedFiles = compareCommits.data.files.map(file => file.filename);
          console.log('Changed files:', changedFiles.join('\n'));
          return changedFiles.join('\n')
    - run: |
        echo "${{ steps.file_changes.outputs.result }}"
        echo "FILES=${{ steps.file_changes.outputs.result }}" >> $GITHUB_ENV
        

    - name: display-item
      run: echo ${{env.FILES}}
